/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package serpientesescaleras;

import javax.swing.JOptionPane;

/**
 *
 * @author maryza
 */
public class Start extends javax.swing.JFrame {

    /**
     * Creates new form Start
     */
    public Start() {
        initComponents();
        ocultar();
       // ocultarFichas();
    }
    public void ocultarFichas(){
    jLabel1.setVisible(false);
    jLabel2.setVisible(false);
    jLabel3.setVisible(false);
    jLabel4.setVisible(false);
    jLabel5.setVisible(false);
    jLabel6.setVisible(false);
    jLabel7.setVisible(false);
    jLabel8.setVisible(false);
    jLabel9.setVisible(false);
    jLabel10.setVisible(false);
    jLabel11.setVisible(false);
    jLabel12.setVisible(false);
    jLabel13.setVisible(false);
    jLabel14.setVisible(false);
    jLabel15.setVisible(false);
    jLabel16.setVisible(false);
    jLabel17.setVisible(false);
    jLabel18.setVisible(false);
    jLabel19.setVisible(false);
    jLabel20.setVisible(false);
    jLabel21.setVisible(false);
    jLabel22.setVisible(false);
    jLabel23.setVisible(false);
    jLabel24.setVisible(false);
    jLabel25.setVisible(false);
    jLabel26.setVisible(false);
    jLabel27.setVisible(false);
    jLabel28.setVisible(false);
    jLabel29.setVisible(false);
    jLabel30.setVisible(false);
    }
        public void ocultar() {
        btn_tirarDado.setVisible(false);
        Jlb_jugador1.setVisible(false);
        Jlb_namejuga1.setVisible(false);
        lbl_aleatorio.setVisible(false);
        Jlb_maquina.setVisible(false);
        Jlb_namejuga2.setVisible(false);
        Jlb_maquina1.setVisible(false);
        Jlb_jugador1.setVisible(false);
        Jlb_jugador.setVisible(false);
        btn_salir.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jlb_jugador1 = new javax.swing.JLabel();
        Jlb_jugador = new javax.swing.JLabel();
        Jlb_maquina1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tablero = new javax.swing.JLabel();
        lbl_aleatorio = new javax.swing.JLabel();
        btn_tirarDado = new javax.swing.JButton();
        Jlb_namejuga1 = new javax.swing.JLabel();
        Jlb_namejuga2 = new javax.swing.JLabel();
        Jlb_maquina = new javax.swing.JLabel();
        Btn_Jugar = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Jlb_jugador1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/J1.png"))); // NOI18N
        Jlb_jugador1.setText("jLabel1");
        getContentPane().add(Jlb_jugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 510, 40, 37));

        Jlb_jugador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/J1.png"))); // NOI18N
        Jlb_jugador.setText("jLabel1");
        getContentPane().add(Jlb_jugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 150, 40, 37));

        Jlb_maquina1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/J2.png"))); // NOI18N
        Jlb_maquina1.setText("jLabel1");
        getContentPane().add(Jlb_maquina1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 40, 37));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 480, 70, 60));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 480, 60, 50));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 480, 70, 60));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 480, 60, 50));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 480, 60, 50));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 370, 60, 50));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(581, 370, 60, 50));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 370, 80, 50));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 60, 60));
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 60, 60));
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 80, 70));
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 70, 60));
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 70, 70));
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 70, 60));
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 260, 60, 50));
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 240, 60, 50));
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 260, 50, 60));
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 160, 70, 60));
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, 70, 50));
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, 60, 50));
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 80, 60));
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 80, 50));
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 70, 60));
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 70, 60));
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 70, 70));
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 80, 60));
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 90, 60));
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, 60, 50));
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, 70, 50));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 456, 50, 30));

        tablero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/escalera.jpg"))); // NOI18N
        getContentPane().add(tablero, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 818, 561));

        lbl_aleatorio.setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().add(lbl_aleatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 290, 86, 26));

        btn_tirarDado.setText("Tirar Dado");
        btn_tirarDado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tirarDadoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_tirarDado, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 220, -1, 40));

        Jlb_namejuga1.setText("jLabel1");
        getContentPane().add(Jlb_namejuga1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 170, -1, -1));

        Jlb_namejuga2.setText("jLabel1");
        getContentPane().add(Jlb_namejuga2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 120, -1, -1));

        Jlb_maquina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/J2.png"))); // NOI18N
        Jlb_maquina.setText("jLabel1");
        getContentPane().add(Jlb_maquina, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 100, 40, 37));

        Btn_Jugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Play.png"))); // NOI18N
        Btn_Jugar.setText("Jugar");
        Btn_Jugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_JugarActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Jugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 10, 90, 50));

        btn_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/cerrar.png"))); // NOI18N
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        getContentPane().add(btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 500, 60, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_tirarDadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tirarDadoActionPerformed
        Math.random();
        double name = Math.random() * 6 + 1;
        int numeroAleatorio = (int) (Math.random() * 6 + 1);
        lbl_aleatorio.setVisible(true);
        String dato = Integer.toString(numeroAleatorio);
        lbl_aleatorio.setText(dato);
       // Jl1.setVisible(true);

        Jlb_jugador1.setVisible(true);
        Jlb_maquina.setVisible(true);

        //System.out.println("Numero aleatorio:"+numeroAleatorio);
    }//GEN-LAST:event_btn_tirarDadoActionPerformed

    private void Btn_JugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_JugarActionPerformed
        String nombre;
        nombre=JOptionPane.showInputDialog("Ingresa nombre del primer Jugador: ");
        Jlb_namejuga1.setText(nombre);
        btn_tirarDado.setVisible(true);
        Jlb_jugador.setVisible(true);
        Jlb_jugador1.setVisible(true);
        Jlb_namejuga1.setVisible(true);
        Jlb_maquina.setVisible(true);
        Jlb_namejuga2.setVisible(true);
        Jlb_namejuga2.setText("PC");
        btn_tirarDado.setVisible(true);
        //inicalizando img en casilla 1
        Jlb_maquina1.setVisible(true);
        Jlb_jugador1.setVisible(true);   
        btn_salir.setVisible(true);
    }//GEN-LAST:event_Btn_JugarActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Start().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Jugar;
    private javax.swing.JLabel Jlb_jugador;
    private javax.swing.JLabel Jlb_jugador1;
    private javax.swing.JLabel Jlb_maquina;
    private javax.swing.JLabel Jlb_maquina1;
    private javax.swing.JLabel Jlb_namejuga1;
    private javax.swing.JLabel Jlb_namejuga2;
    private javax.swing.JButton btn_salir;
    private javax.swing.JButton btn_tirarDado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbl_aleatorio;
    private javax.swing.JLabel tablero;
    // End of variables declaration//GEN-END:variables
}
